# Generated by Django 4.2.1 on 2023-06-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='poster',
        ),
    ]
